replicaCount: 1

image:
  repository: dajudge/s3-resource-operator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
