name: Format Artifact

on:
  pull_request:

permissions:
  contents: read

jobs:
  format-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Apply Spotless
        run: mvn --batch-mode --no-transfer-progress -Pformat spotless:apply
      - name: Upload formatted sources
        uses: actions/upload-artifact@v4
        with:
          name: formatted-sources
          path: src/test/java/com/dajudge/s3operator/*.java
          if-no-files-found: error
